const emitterControlsConfig = [
    {
        'id': 'emitter-x',
        'title': 'Emitter X',
        'entityValue': 'x',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': 'X-min',
        'label2': 'X-max',
        'initVal': 0,
        'helpText': 'The X position of the emitter on the canvas, 0 is the left edge, 1000 is the right edge. Mid position is the canvas centre.'
    },
    {
        'id': 'emitter-y',
        'title': 'Emitter Y',
        'entityValue': 'y',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'Y-min',
        'label2': 'Y-max',
        'initVal': 0,
        'helpText': 'The Y position of the emitter on the canvas, 0 is the top edge, 1000 is the bottom edge. Mid position is the canvas centre.'
    },
    {
        'id': 'emitter-x-vel',
        'title': 'Emitter X Velocity',
        'entityValue': 'xVel',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': 'X-min',
        'label2': 'X-max',
        'initVal': 0,
        'helpText': 'The X velocity of the emitter, 0 is no movement, 1000 is the fastest possible movement.'
    },
    {
        'id': 'emitter-y-vel',
        'title': 'Emitter Y Velocity',
        'entityValue': 'yVel',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'Y-min',
        'label2': 'Y-max',
        'initVal': 0,
        'helpText': 'The Y velocity of the emitter, 0 is no movement, 1000 is the fastest possible movement.'
    },
    {
        'id': 'emitter-direction-rad',
        'title': 'Emitter Direction',
        'entityValue': 'rad',
        'entityValuePath': 'emissionOpts.direction',
        'type': 'range',
        'min': 0,
        'max': 2,
        'step': 0.0001,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '1',
        'initVal': 0,
        'helpText': 'The direction of the particles emitted from the emitter, in radians. 0 is up, 0.5 is right, 1 is down, 1.5 is left.'
    },
    {
        'id': 'emitter-direction-min',
        'title': 'Emitter Direction Min',
        'entityValue': 'min',
        'entityValuePath': 'emissionOpts.direction',
        'type': 'range',
        'min': 0,
        'max': 2,
        'step': 0.0001,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '2',
        'initVal': 0,
        'helpText': 'The minimum direction of the particles emitted from the emitter, in radians. 0 is up, 0.5 is right, 1 is down, 1.5 is left.'
    },
    {
        'id': 'emitter-direction-max',
        'title': 'Emitter Direction Max',
        'entityValue': 'max',
        'entityValuePath': 'emissionOpts.direction',
        'type': 'range',
        'min': 0,
        'max': 2,
        'step': 0.0001,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '2',
        'initVal': 0,
        'helpText': 'The maximum direction of the particles emitted from the emitter, in radians. 0 is up, 0.5 is right, 1 is down, 1.5 is left.'
    },
    {
        'id': 'emitter-radial',
        'title': 'Emitter Radial Displacement',
        'entityValue': 'radialDisplacement',
        'entityValuePath': 'emissionOpts',
        'type': 'range',
        'min': 0,
        'max': 2000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '2000',
        'initVal': 0,
        'helpText': 'The radial displacement of the particles emitted from the emitter, i.e. how far from the emmiter origin the particle will be emiited. 0 is no displacement, 2000 is the maximum displacement.'
    },
    {
        'id': 'emitter-radial-offset',
        'title': 'Emitter Radial Displacement Offset',
        'entityValue': 'radialDisplacementOffset',
        'entityValuePath': 'emissionOpts',
        'type': 'range',
        'min': 0,
        'max': 200,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '200',
        'initVal': 0,
        'helpText': 'The radial displacement offset randomises the radial displacement of the particle emission with 0 being the original radial displacement, greater values will be applied as a range either inside or ouside of the radial displacement.'
    },
    {
        'id': 'emitter-impulse-pow',
        'title': 'Emitter Impulse Power',
        'entityValue': 'pow',
        'entityValuePath': 'emissionOpts.impulse',
        'type': 'range',
        'min': 0,
        'max': 200,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '200',
        'initVal': 0,
        'helpText': 'The impulse power of the particles emitted from the emitter, i.e. how fast the particles are emitted. 0 is no impulse, 200 is the maximum impulse.'
    },
    {
        'id': 'emitter-impulse-pow-min',
        'title': 'Emitter Impulse Power Min',
        'entityValue': 'min',
        'entityValuePath': 'emissionOpts.impulse',
        'type': 'range',
        'min': 0,
        'max': 200,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '200',
        'initVal': 0,
        'helpText': 'The minimum impulse power of the particles emitted from the emitter, i.e. how fast the particles are emitted. 0 is no impulse, 200 is the maximum impulse.'
    },
    {
        'id': 'emitter-impulse-pow-max',
        'title': 'Emitter Impulse Power Max',
        'entityValue': 'max',
        'entityValuePath': 'emissionOpts.impulse',
        'type': 'range',
        'min': 0,
        'max': 200,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': '0',
        'label2': '200',
        'initVal': 0,
        'helpText': 'The maximum impulse power of the particles emitted from the emitter, i.e. how fast the particles are emitted. 0 is no impulse, 200 is the maximum.'
    },
    {
        'id': 'emitter-rate-min',
        'title': 'Emitter Rate Min',
        'entityValue': 'rateMin',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The minimum rate of particle emission from the emitter, 0 is no particles, 1000 is the maximum rate.'
    },
    {
        'id': 'emitter-rate-max',
        'title': 'Emitter Rate Max',
        'entityValue': 'rateMax',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 1000,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': false,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The maximum rate of particle emission from the emitter, 0 is no particles, 1000 is the maximum rate.'
    },
    {
        'id': 'emitter-rate-decay',
        'title': 'Emitter Rate Decay',
        'entityValue': 'rateDecay',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 360,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The rate at which the particle emission rate will reduce after each emission. 0 is no reduction, 360 is the maximum reduction.'
    },
    {
        'id': 'emitter-rate-decay-max',
        'title': 'Emitter Rate Decay Max',
        'entityValue': 'rateDecayMax',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 360,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The threshold at which the particle emission rate will no longer reduce after each emission. 0 is no reduction, 360 is the maximum reduction.'
    },
    {
        'id': 'emitter-rate-repeat',
        'title': 'Emitter Repeat Rate',
        'entityValue': 'repeatRate',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 360,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The rate at which the particle emission repeat rate will increase after each emission. 0 is no increase, 360 is the maximum increase.'
    },
    {
        'id': 'emitter-rate-repeat-decay',
        'title': 'Emitter Repeat Rate decay',
        'entityValue': 'repeatDecayMaX',
        'entityValuePath': '',
        'type': 'range',
        'min': 0,
        'max': 360,
        'step': 1,
        'multiplier': 1,
        'controller': 'emitter',
        'flipped': true,
        'label1': 'min',
        'label2': 'max',
        'initVal': 0,
        'helpText': 'The rate at which the particle emission repeat rate will reduce after each emission. 0 is no reduction, 360 is the maximum reduction.'
    }
];

export { emitterControlsConfig };